[package]
name = "tensorman"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
bitflags = "1.2"
nix = "0.15"
fern = "0.5"
tabular = "0.1"
xdg = "2.2"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
bollard = { version = "0.3", features = ["tls"] }
failure = "0.1"
tokio = "0.1"
futures = "0.1"
chrono = "0.4"
dirs = "2.0"
thiserror = "1.0.3"
anyhow = "1.0.19"
